### PR TITLE
Add metrics

### PR DESCRIPTION
**Pull request by ivanyu**
This commit adds only one metric--segment copies per second--but it lays the foundation for further adding more metrics.

### CODE REVIEW

**Review by jeqo — COMMENTED** [review]
Looks good overall, just a couple of comments regarding implementation:

Yammer version used by Kafka is quite old and kept for compatibility issues: 
- https://issues.apache.org/jira/browse/KAFKA-8721
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-510%3A+Metrics+library+upgrade

Could we state why using this library instead of https://kafka.apache.org/33/javadoc/org/apache/kafka/common/metrics/Metrics.html?

PS. I have bumped [KIP-877](https://cwiki.apache.org/confluence/display/KAFKA/KIP-877%3A+Mechanism+for+plugins+and+connectors+to+register+metrics) thread as it should be the idea way to add plugin specific metrics.

**Comment by ivanyu** [comment]
@jeqo I just didn't think about this. Thank you for pointing this out. Despite I like the old style MBean hierarchy :) I'll switch to the `Metrics`: no need to borrow code in this case.

**Comment by ivanyu** [comment]
Thanks again @jeqo, it turned out simpler and shorter :)

**Review by jeqo — APPROVED** [review]
LGTM!

Non-blocking: to follow Metrics usage across Kafka code-base, we may want to have:
- *Metrics: collection of sensors, similar to https://github.com/apache/kafka/blob/f7db6031b84a136ad0e257df722b20faa7c37b8a/clients/src/main/java/org/apache/kafka/clients/producer/internals/Sender.java#L870
- *MetricsRegistry: collection of metric name templates, similar to https://github.com/apache/kafka/blob/01ab888dbd08ccd4b0de9333d21581ce24fe2c3b/clients/src/main/java/org/apache/kafka/clients/producer/internals/SenderMetricsRegistry.java

but we can surely do it later once more metrics are added

**Pull request merged**
